"""empty message

Revision ID: 34ab1a371f2e
Revises: 6463656170ac
Create Date: 2021-02-25 14:32:57.245978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ab1a371f2e'
down_revision = '6463656170ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('url_image', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'url_image')
    # ### end Alembic commands ###
