"""empty message

Revision ID: 6463656170ac
Revises: 25911c61bfa4
Create Date: 2021-02-25 14:08:21.168822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6463656170ac'
down_revision = '25911c61bfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('url_image', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'url_image')
    # ### end Alembic commands ###
