"""empty message

Revision ID: cc3faa006e93
Revises: 34ab1a371f2e
Create Date: 2021-02-26 14:40:02.410244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3faa006e93'
down_revision = '34ab1a371f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('latitude', sa.String(length=50), nullable=True))
    op.add_column('points', sa.Column('longitude', sa.String(length=50), nullable=True))
    op.drop_column('points', 'coordinates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('coordinates', sa.VARCHAR(length=250), nullable=False))
    op.drop_column('points', 'longitude')
    op.drop_column('points', 'latitude')
    # ### end Alembic commands ###
